model: openai/gpt-4.1
architect: true
auto-accept-architect: false
weak-model: openai/gpt-4.1
editor-model: openai/gpt-4.1

user-input-color: '#c6a0f6'
tool-output-color: "#8bd5ca"
tool-error-color: "#ed8796"
tool-warning-color: "#f5a97f"
assistant-output-color: "#8aadf4"
completion-menu-color: '#cad3f5'
completion-menu-bg-color: "#24273a"
completion-menu-current-color: "#24273a"
completion-menu-current-bg-color: "#a6da95"
code-theme: dracula-dark

git: true
auto-commits: false
attribute-author: false
attribute-committer: false
attribute-commit-message-author: false
attribute-commit-message-committer: false

suggest-shell-commands: false
detect-urls: false

vim: true
