gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#3ddbd9"
      - "bold"
    inactiveBorderColor:
      - "#08bdba"
    searchingActiveBorderColor:
      - "#3ddbd9"
      - "bold"
    optionsTextColor:
      - "#78a9ff"
    selectedLineBgColor:
      - "#404040"
    cherryPickedCommitFgColor:
      - "#78a9ff"
    cherryPickedCommitBgColor:
      - "#be95ff"
    markedBaseCommitFgColor:
      - "#78a9ff"
    markedBaseCommitBgColor:
      - "#42be65"
    unstagedChangesColor:
      - "#ee5396"
    defaultFgColor:
      - "#d5d5d5"
git:
  autoFetch: false
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
promptToReturnFromSubprocess: false
customCommands:
  - key: "<c-a>" # Keybinding (Ctrl + a)
    description: "AI Commit"
    command: "source ~/.config/zsh/functions/ai-tools.zsh && ai_commit"
    context: "global"
    output: terminal
