gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - '#83A598'  # blue_lite from hard variant
      - bold
    inactiveBorderColor:
      - '#A89984'  # fg4 from hard variant
    optionsTextColor:
      - '#8EC07C'  # aqua_lite from hard variant
    selectedLineBgColor:
      - '#3C3836'  # bg1 from hard variant
    selectedRangeBgColor:
      - '#504945'  # bg2 from hard variant
    cherryPickedCommitBgColor:
      - '#665C54'  # bg3 from hard variant
    cherryPickedCommitFgColor:
      - '#FABD2F'  # yellow_lite from hard variant
    unstagedChangesColor:
      - '#FB4934'  # red_lite from hard variant
    defaultFgColor:
      - '#FBF1C7'  # fg from hard variant
    searchingActiveBorderColor:
      - '#FE8019'  # orange_lite from hard variant
git:
  autoFetch: false
  paging:
    colorArg: always
    pager: delta --dark --paging=never
customCommands:
  - key: '<c-a>'
    context: 'global'
    command: "oco --yes"
