gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#fabd2f"
      - "bold"
    inactiveBorderColor:
      - "#8ec07c"
    searchingActiveBorderColor:
      - "#fabd2f"
      - "bold"
    optionsTextColor:
      - "#83a598"
    selectedLineBgColor:
      - "#504945"
    cherryPickedCommitFgColor:
      - "#83a598"
    cherryPickedCommitBgColor:
      - "#d3869b"
    markedBaseCommitFgColor:
      - "#83a598"
    markedBaseCommitBgColor:
      - "#b8bb26"
    unstagedChangesColor:
      - "#fb5944"
    defaultFgColor:
      - "#ebdbb2"
git:
  autoFetch: false
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
promptToReturnFromSubprocess: false
customCommands:
  - key: "<c-a>" # Keybinding (Ctrl + a)
    description: "AI Commit"
    command: "source ~/.config/zsh/functions/ai-tools.zsh && ai_commit"
    context: "global"
    output: terminal
