alias v="nvim" # Quick nvim alias
alias l='eza -lah --icons auto'               # Detailed list with icons and human-readable sizes
alias ls='eza -lah --icons auto --total-size' # Same as above with total directory size
alias cat="bat -p"                       # Use bat (syntax-highlighted cat) in plain mode
alias y='yazi'                           # Yazi file manager
alias ld='lazydocker' # Docker management TUI
alias lg='lazygit'    # Git management TUI
alias qq="exit" # Quick exit alias
alias p='pulumi'   # Infrastructure as Code tool
alias pp='pulumi preview' # Pulumi preview command
alias pup='pulumi up --yes --skip-preview'      # Pulumi update command
alias pr='pulumi refresh --yes --skip-preview' # Pulumi refresh command
alias rpi='pi --provider github-copilot --model gpt-5.4'
alias cpi='pi --provider crof --model glm-5.2'
alias tf='terraform' # Terraform command
alias smd='specmd'   # Create spec.md from template
alias rmd='reviewmd'  # Create review.md from template
alias c='claude'
alias t='tmux'
alias k='kubectl'
