theme = "catppuccin_mocha"

[editor]
true-color = true

[keys.normal]
0 = "goto_line_start"
"$" = "goto_line_end"
";" = "command_mode"
q = { q = ":quit" }

[keys.normal.space]
b = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = true
follow-symlinks = true
git-ignore = true
