version: "2"

linters:
  default: all
  disable:
    - tagliatelle
    - testpackage
    - gomodguard
    - depguard
    - godot
    - exhaustruct
    - wsl
    - wsl_v5
    - funlen
    - noinlineerr
    - forbidigo
    - revive
    - nilnil
    - ireturn
    - gochecknoglobals
    - err113

  settings:
    perfsprint:
      string-format: false
    gosec:
      excludes:
        - G204 #  Subprocess launched with variable
    cyclop:
      # The maximal code complexity to report.
      max-complexity: 15
    lll:
      line-length: 150
    # gomoddirectives:
    #   replace-local: true
    #   replace-allow-list:
    #     - github.com/footholdtech/axiom-infrastructure/sdk
    #     - github.com/footholdtech/pulumi-azure/sdk

  exclusions:
    rules:
      - linters:
          - varnamelen
        text: variable name (.+) is too short for the scope of its usage
      - linters:
          - godoclint
        text: godoc should start with symbol name \(\".+\"\)
