font_family      FiraCode Nerd Font
fallback_family Noto Color Emoji
bold_font        auto
allow_color_fonts yes
italic_font      auto
bold_italic_font auto
font_size  11

#clipboard_control write-clipboard write-primary read-clipboard-ask read-primary-ask
clipboard_control write-primary write-clipboard read-clipboard read-primary # no-append

map shift+enter send_text all \x1b[13;2u

map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5
map alt+6 goto_tab 6
map alt+7 goto_tab 7
map alt+8 goto_tab 8
map alt+9 goto_tab 9

map alt+- launch --location=hsplit --cwd root
map alt+shift+\ launch --location=vsplit --cwd root

# Move the active window in the indicated direction
map alt+up neighboring_window up
map alt+left neighboring_window left
map alt+right neighboring_window right
map alt+down neighboring_window down
map alt+k neighboring_window up
map alt+h neighboring_window left
map alt+l neighboring_window right
map alt+j neighboring_window down

map alt+shift+, resize_window narrower 3
map alt+shift+. resize_window wider 3
map alt+shift+= resize_window taller 3
map alt+shift+- resize_window shorter 3

map alt+shift+up move_window up
map alt+shift+left move_window left
map alt+shift+right move_window right
map alt+shift+down move_window down

#map ctrl+shift+t launch --type tab --cwd root --location neighbor

map alt+shift+f toggle_layout stack

enabled_layouts splits,stack

remember_window_size  yes

hide_window_decorations yes

# window_border_width 5pt
# active_border_color #00ff00
window_padding_width 0.0

# fg
foreground           #d3c6aa
# bg0
background           #2d353b
# grey2
title_fg             #9da9a0

# bg_dim
title_bg             #232a2e
margin_bg            #232a2e

# grey1
margin_fg            #859289
# bg_dim
filler_bg            #232a2e

# bg_red
removed_bg           #514045
highlight_removed_bg #514045
removed_margin_bg    #514045

# bg_green
added_bg             #425047
highlight_added_bg   #425047
added_margin_bg      #425047

# bg_dim
hunk_margin_bg       #232a2e
hunk_bg              #232a2e

# yellow (fg color for visibility)
search_bg            #dbbc7f
# bg0 (dark text on yellow)
search_fg            #2d353b
# bg_visual
select_bg            #543a48
# fg
select_fg            #d3c6aa

allow_remote_control yes
listen_on unix:/tmp/kitty

bell_on_tab             yes
tab_bar_edge            top
tab_title_template       {index}: {title}
active_tab_foreground   #2d353b
active_tab_background   #a7c080
active_tab_font_style   bold
inactive_tab_foreground #9da9a0
inactive_tab_background #343f44
inactive_tab_font_style normal
tab_bar_style custom
#tab_powerline_style slanted
